### ISSUE TITLE
Update ComposerInformation for Mage-OS vendor name

### ISSUE THREAD

**Issue by Vinai** [mage-os/mageos-magento2#42]
The class `Magento\Framework\Composer\ComposerInformation` needs to be updated so it checks for the vendor name `mage-os` instead of `magento`.

### Preconditions and environment

- Mage-OS 1.0.0 preview

### Steps to reproduce

Log into the admin and inspect the footer. 

### Expected result

I expect to see the `Mage-OS ver. 1.0.0`.

### Actual result

I see `Mage-OS ver. UNKNOWN`.

### Additional information

There are a number of regular expressions that need to be updated so they match the vendor-name `mage-os`:

* `\Magento\Framework\Composer\ComposerInformation::getRequiredPhpVersion`
* `\Magento\Framework\Composer\ComposerInformation::isSystemPackage`
* `\Magento\Framework\Composer\ComposerInformation::isMagentoRoot`

Also, the tests in `dev/tests/integration/testsuite/Magento/Framework/Composer/ComposerInformationTest.php` need to be adjusted accordingly.

**Comment by fballiano** [comment]
Fixed by https://github.com/mage-os/mageos-magento2/pull/48
