### ISSUE TITLE
Remove adobe data-collection code and modal

### ISSUE THREAD

**Issue by Vinai** [mage-os/mageos-magento2#43]
Both the adobe data-collection modal and the code to collect the data should be removed.

### Preconditions and environment

- Mage-OS 1.0.0 preview

### Steps to reproduce

Install the 1.0.0 preview and log into the backend as an admin user.

### Expected result

I see the admin dashboard.

### Actual result

I see the data-collection agreement modal dialog.

<img width="750" alt="Bildschirmfoto 2023-10-08 um 08 02 43" src="https://github.com/mage-os/mageos-magento2/assets/72463/788318b1-6694-4480-bc43-cee280adc7bd">

**Comment by rhoerr** [comment]
Are we looking to remove those specific aspects, or the entire AdminAnalytics module? I believe that's the entire purpose of the module. https://github.com/mage-os/mageos-magento2/tree/2.4-develop/app/code/Magento/AdminAnalytics

The package code is `magento/module-admin-analytics`

**Comment by Vinai** [comment]
Removing it would be best, however, because of upstream compatibility we maybe could keep it but short-circuit all functionality?

**Comment by Vinai** [comment]
Or, maybe we remove it after all, since resolving merge conflicts with upstream will probably be rather simple :)

**Comment by Vinai** [comment]
Reopening because the tracking URL still needs to be removed.

**Comment by Vinai** [comment]
The modal is still showing upon the first login.

It is a ui component, so making the block depend on the configuration flag didn't do the trick.
In app/code/Magento/AdminAnalytics/view/adminhtml/layout/adminhtml_dashboard_index.xml:
```
<uiComponent name="admin_usage_notification" ifconfig="admin/usage/enabled">
```
may do the trick.

**Comment by Vinai** [comment]
The modal still displays, because the default config value is evaluated as `" 0 "`, which is `true` when used with `isSetFlag`. Without wrapping space it evaluates correctly to `false`.
